run installation completely once to be cached

diff --git a/.github/workflows/generate_documentation.yml b/.github/workflows/generate_documentation.yml
--- a/.github/workflows/generate_documentation.yml
+++ b/.github/workflows/generate_documentation.yml
@@ -63,50 +63,50 @@ jobs:
       run: |
         conda list
 
-    - name: Build documentation
-      run: |
-        cd docs
-        make html
-
-    #    - uses: ammaraskar/sphinx-action@master
-    #      with:
-    #        docs-folder: "docs/"
-    # Example of using a custom build-command.
-    #    - uses: ammaraskar/sphinx-action@master
-    #      with:
-    #        build-command: "sphinx-build -b html . _build"
-    #        docs-folder: "docs/"
-    # Great extra actions to compose with:
-    # Create an artifact of the html output.
-    - uses: actions/upload-artifact@v1
-      with:
-        name: DocumentationHTML
-        path: docs/_build/html/
-
-    - uses: actions/checkout@v3
-
-#    - name: Configure git remote to host documentation
+#    - name: Build documentation
 #      run: |
-#        git remote add ghBEP git@github.com:BEP032/BEP032-examples.git
-#        git fetch ghBEP
-
-    # Publish built docs to gh-pages branch.
-    # ===============================
-    - name: Commit documentation changes
-      run: |
-        git checkout -b gh-pages origin/gh-pages
-        git merge add/doc  # TODO: This needs to be master later on
-        cp -r docs/_build/html/* gh-pages/
-        cd gh-pages
-        touch .nojekyll
-        git add .
-        git add docs/tutorials
-        git commit -m "Update documentation" -a || true
-        # The above command will fail if no changes were present, so we ignore
-        # that.
-
-    - name: Push changes
-      run: |
-        git push ghBEP gh-pages
-        branch: gh-pages
-    # ===============================
+#        cd docs
+#        make html
+#
+#    #    - uses: ammaraskar/sphinx-action@master
+#    #      with:
+#    #        docs-folder: "docs/"
+#    # Example of using a custom build-command.
+#    #    - uses: ammaraskar/sphinx-action@master
+#    #      with:
+#    #        build-command: "sphinx-build -b html . _build"
+#    #        docs-folder: "docs/"
+#    # Great extra actions to compose with:
+#    # Create an artifact of the html output.
+#    - uses: actions/upload-artifact@v1
+#      with:
+#        name: DocumentationHTML
+#        path: docs/_build/html/
+#
+#    - uses: actions/checkout@v3
+#
+##    - name: Configure git remote to host documentation
+##      run: |
+##        git remote add ghBEP git@github.com:BEP032/BEP032-examples.git
+##        git fetch ghBEP
+#
+#    # Publish built docs to gh-pages branch.
+#    # ===============================
+#    - name: Commit documentation changes
+#      run: |
+#        git checkout -b gh-pages origin/gh-pages
+#        git merge add/doc  # TODO: This needs to be master later on
+#        cp -r docs/_build/html/* gh-pages/
+#        cd gh-pages
+#        touch .nojekyll
+#        git add .
+#        git add docs/tutorials
+#        git commit -m "Update documentation" -a || true
+#        # The above command will fail if no changes were present, so we ignore
+#        # that.
+#
+#    - name: Push changes
+#      run: |
+#        git push ghBEP gh-pages
+#        branch: gh-pages
+#    # ===============================
